services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: brainquest
      POSTGRES_USER: brainquest
      POSTGRES_PASSWORD: brainquest
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"